import type { NextPage } from 'next'
import Head from 'next/head'
import { Grid } from '@mui/material'

import { Layout } from '../components/Layout'
import { TokenCard } from '../components/TokenCard'
import { FormCard } from '../components/FormCard'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Oazo Apps Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Grid container spacing={2}>
          <Grid item sm={5}>
            <TokenCard />
          </Grid>
          <Grid item sm={7}>
            <FormCard />
          </Grid>
        </Grid>
      </Layout>
    </div>
  )
}

export default Home
